FROM php:8.5-fpm-alpine

ADD --chmod=0755 \
    https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions \
    /usr/local/bin/

RUN install-php-extensions \
        pdo_mysql \
        bcmath \
        intl \
        gd \
        zip \
        pcntl \
        opcache \
        redis \
    && apk add --no-cache git curl unzip nodejs npm \
    && curl -sS https://getcomposer.org/installer \
        | php -- --install-dir=/usr/local/bin --filename=composer \
    && rm -rf /var/cache/apk/* /tmp/pear

COPY .docker/php.dev.ini  /usr/local/etc/php/conf.d/99-app.ini
COPY .docker/fpm.dev.conf /usr/local/etc/php-fpm.d/zzz-app.conf

WORKDIR /var/www/app

CMD ["php-fpm"]
